version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    volumes:
      - "./volumes/db:/data/postgres"
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

volumes:
  postgres:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "./volumes/db"

networks:
  postgres: